
route:
  group_by: [ alertname ]
  receiver: 'EDA' # default receiver
  repeat_interval: 24h
  routes:

receivers:
  - name: 'EDA'
    webhook_configs:
      #- url: 'http://172.190.170.87:5000/alerts'
      - url: 'http://172.20.34.72:5000/alerts'
